users-api:
 ribbon:
  listOfServers: http://localhost:3000

feign:
 client:
  config:
   default:
    connectTimeout: 500000
    readTimeout: 500000

restTemplate:
 connectTimeout: 500000
 readTimeout: 500000

